#!/usr/bin/env bash
set -e

testname=$(basename $1);
cd tests/$testname
echo "Running test $testname..."

source ./config

cleanup() {
    if [[ -n "$CLEANUP" ]]; then
        $CLEANUP
    fi
}

fail() {
    echo "$@" >&2
    exit 1
}

cleanup
set +e
../../djconvert $COMMAND >STDOUT 2>STDERR
echo "$?" > CODE
set -e

ls -a > FILES

for filename in ${COMPARE[@]}; do
    diff "$filename" "${filename}.expected" \
        || fail "Compare failed for $filename";
done

cleanup

echo "$testname: PASS"
